=== JukeboxMC/BedrockBlockUpgradeSchema/upgrade_schema/schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$defs": {
		"blockStateProperty": {
			"type": "object",
			"properties": {
				"type": {
					"enum": ["string", "int", "byte"]
				},
				"value": {
					"type": ["string", "integer"]
				}
			}
		}
	},
	"type": "object",
	"additionalProperties": false,
	"required": [
		"maxVersionMajor",
		"maxVersionMinor",
		"maxVersionPatch",
		"maxVersionRevision"
	],
	"properties": {
		"maxVersionMajor": {
			"type": "integer",
			"minValue": 0
		},
		"maxVersionMinor": {
			"type": "integer",
			"minValue": 0
		},
		"maxVersionPatch": {
			"type": "integer",
			"minValue": 0
		},
		"maxVersionRevision": {
			"type": "integer",
			"minValue": 0
		},
		"renamedIds": {
			"type": "object",
			"additionalProperties": {
				"type": "string"
			}
		},
		"renamedProperties": {
			"type": "object",
			"additionalProperties": {
				"type": "object",
				"additionalProperties": {
					"type": "string"
				}
			}
		},
		"addedProperties": {
			"type": "object",
			"additionalProperties": {
				"type": "object",
				"additionalProperties": {
					"$ref": "#/$defs/blockStateProperty"
				}
			}
		},
		"removedProperties": {
			"type": "object",
			"additionalProperties": {
				"type": "array",
				"items": {
					"type": "string"
				}
			}
		},
		"remappedPropertyValues": {
			"type": "object",
			"additionalProperties": {
				"type": "object",
				"additionalProperties": {
					"type": "string"
				}
			}
		},
		"remappedPropertyValuesIndex": {
			"type": "object",
			"additionalProperties": {
				"type": "array",
				"items": {
					"type": "object",
					"properties": {
						"old": {
							"$ref": "#/$defs/blockStateProperty"
						},
						"new": {
							"$ref": "#/$defs/blockStateProperty"
						}
					}
				}
			}
		},
		"remappedStates": {
			"type": "object",
			"additionalProperties": {
				"type": "array",
				"items": {
					"type": "object",
					"properties": {
						"oldState": {
							"type": "object",
							"additionalProperties": {
								"$ref": "#/$defs/blockStateProperty"
							}
						},
						"newId": {
							"type": "string"
						},
						"newState": {
							"type": "object",
							"additionalProperties": {
								"$ref": "#/$defs/blockStateProperty"
							}
						}
					}
				}
			}
		}
	}
}

=== JukeboxMC/BedrockBlockUpgradeSchema/nbt_upgrade_schema/0041_1.14.0_to_1.16.0.57_beta.json
{
    "maxVersionMajor": 1,
    "maxVersionMinor": 16,
    "maxVersionPatch": 0,
    "maxVersionRevision": 0,
    "addedProperties": {
        "minecraft:cobblestone_wall": {
            "wall_connection_type_east": {
                "type": "string",
                "value": "none"
            },
            "wall_connection_type_north": {
                "type": "string",
                "value": "none"
            },
            "wall_connection_type_south": {
                "type": "string",
                "value": "none"
            },
            "wall_connection_type_west": {
                "type": "string",
                "value": "none"
            },
            "wall_post_bit": {
                "type": "byte",
                "value": 0
            }
        },
        "minecraft:jigsaw": {
            "rotation": {
                "type": "int",
                "value": 0
            }
        }
    }
}

=== JukeboxMC/BedrockBlockUpgradeSchema/nbt_upgrade_schema/0121_1.18.10_to_1.18.20.27_beta.json
{
    "maxVersionMajor": 1,
    "maxVersionMinor": 18,
    "maxVersionPatch": 10,
    "maxVersionRevision": 1,
    "addedProperties": {
        "minecraft:ochre_froglight": {
            "pillar_axis": {
                "string": "y"
            }
        },
        "minecraft:pearlescent_froglight": {
            "pillar_axis": {
                "string": "y"
            }
        },
        "minecraft:verdant_froglight": {
            "pillar_axis": {
                "string": "y"
            }
        }
    }
}

=== JukeboxMC/BedrockBlockUpgradeSchema/upgrade_schema/0011_1.10.0_to_1.12.0.json
{
    "maxVersionMajor": 1,
    "maxVersionMinor": 12,
    "maxVersionPatch": 0,
    "maxVersionRevision": 1,
    "addedProperties": {
        "minecraft:barrel": {
            "open_bit": {
                "type": "byte",
                "value": 0
            }
        },
        "minecraft:bell": {
            "toggle_bit": {
                "type": "byte",
                "value": 0
            }
        },
        "minecraft:campfire": {
            "direction": {
                "type": "int",
                "value": 0
            },
            "extinguished": {
                "type": "byte",
                "value": 0
            }
        },
        "minecraft:lectern": {
            "powered_bit": {
                "type": "byte",
                "value": 0
            }
        }
    },
    "renamedProperties": {
        "minecraft:blast_furnace": {
            "direction": "facing_direction"
        },
        "minecraft:composter": {
            "fill_level": "composter_fill_level"
        },
        "minecraft:coral_fan": {
            "direction": "coral_fan_direction"
        },
        "minecraft:coral_fan_dead": {
            "direction": "coral_fan_direction"
        },
        "minecraft:smoker": {
            "direction": "facing_direction"
        }
    },
    "remappedPropertyValues": {
        "minecraft:barrel": {
            "facing_direction": "facing_direction_00"
        },
        "minecraft:blast_furnace": {
            "direction": "direction_01"
        },
        "minecraft:smoker": {
            "direction": "direction_01"
        }
    },
    "remappedPropertyValuesIndex": {
        "facing_direction_00": [
            {
                "old": {
                    "type": "int",
                    "value": 7
                },
                "new": {
                    "type": "int",
                    "value": 0
                }
            },
            {
                "old": {
                    "type": "int",
                    "value": 6
                },
                "new": {
                    "type": "int",
                    "value": 0
                }
            }
        ],
        "direction_01": [
            {
                "old": {
                    "type": "int",
                    "value": 0
                },
                "new": {
                    "type": "int",
                    "value": 3
                }
            },
            {
                "old": {
                    "type": "int",
                    "value": 1
                },
                "new": {
                    "type": "int",
                    "value": 4
                }
            },
            {
                "old": {
                    "type": "int",
                    "value": 3
                },
                "new": {
                    "type": "int",
                    "value": 5
                }
            }
        ]
    }
}

=== JukeboxMC/BedrockBlockUpgradeSchema/upgrade_schema/0042_1.16.0_beta_to_1.16.0.json
{
	"maxVersionMajor": 1,
	"maxVersionMinor": 16,
	"maxVersionPatch": 0,
	"maxVersionRevision": 14,
	"renamedIds": {
		"minecraft:blue_fire": "minecraft:soul_fire",
		"minecraft:blue_nether_wart_block": "minecraft:warped_wart_block",
		"minecraft:shroomlight_block": "minecraft:shroomlight",
		"minecraft:weeping_vines_block": "minecraft:weeping_vines",
		"minecraft:basalt_block": "minecraft:basalt",
		"minecraft:polished_basalt_block": "minecraft:polished_basalt",
		"minecraft:soul_soil_block": "minecraft:soul_soil",
		"minecraft:target_block": "minecraft:target",
		"minecraft:crimson_trap_door": "minecraft:crimson_trapdoor",
		"minecraft:lodestone_block": "minecraft:lodestone",
		"minecraft:twisting_vines_block": "minecraft:twisting_vines"
	},
	"removedProperties": {
		"minecraft:blackstone_wall": [
			"wall_block_type"
		],
		"minecraft:polished_blackstone_brick_wall": [
			"wall_block_type"
		],
		"minecraft:polished_blackstone_wall": [
			"wall_block_type"
		]
	}
}

=== JukeboxMC/BedrockBlockUpgradeSchema/upgrade_schema/0071_1.16.0_to_1.16.100.json
{
    "maxVersionMajor": 1,
    "maxVersionMinor": 16,
    "maxVersionPatch": 0,
    "maxVersionRevision": 16,
    "addedProperties": {
        "minecraft:chain": {
            "pillar_axis": {
                "type": "string",
                "value": "y"
            }
        }
    },
    "renamedProperties": {
        "minecraft:bee_nest": {
            "facing_direction": "direction"
        },
        "minecraft:beehive": {
            "facing_direction": "direction"
        }
    },
    "remappedPropertyValues": {
        "minecraft:bee_nest": {
            "facing_direction": "facing_direction_00"
        },
        "minecraft:beehive": {
            "facing_direction": "facing_direction_00"
        }
    },
    "remappedPropertyValuesIndex": {
        "facing_direction_00": [
            {
                "old": {
                    "type": "int",
                    "value": 4
                },
                "new": {
                    "type": "int",
                    "value": 1
                }
            },
            {
                "old": {
                    "type": "int",
                    "value": 3
                },
                "new": {
                    "type": "int",
                    "value": 0
                }
            },
            {
                "old": {
                    "type": "int",
                    "value": 5
                },
                "new": {
                    "type": "int",
                    "value": 3
                }
            },
            {
                "old": {
                    "type": "int",
                    "value": 1
                },
                "new": {
                    "type": "int",
                    "value": 0
                }
            }
        ]
    }
}
